setwd("C:/Tugas Besar")
getwd()
install.packages("C50")
install.packages("printr")
library(C50)
library(printr)
dataset <- read.csv("Shill Bidding Dataset.csv", sep = ",")
dataset$Class<-as.factor(dataset$Class)
class(dataset$Class)
model <- C5.0(Class~., data=dataset)
summary(model)
plot(model)
datatesting <- dataset[,1:12]
predictions <- predict(model, dataset)
table(predictions, dataset$Class)
